name: Docker Publish

on:
  workflow_dispatch:
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'src/**'
      - 'infra/docker/**'
      - 'infra/kubernetes/**'
      - 'infra/terraform/**'
      - '.github/workflows/release.yml'
      - 'tests/**'
  push:
    branches: [ "develop", "master" ]
    paths:
      - 'src/**'
  
env:
  BRANCH_NAME: ${{ github.ref_name }}
  APP_NAME: app_name
  APP_VERSION: latest
  APP_DEV_VERSION: unstable

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Test
        run: go test -v ./tests

## Enable to deploy in develop branch
#   develop:
#     runs-on: ubuntu-latest
#     needs: test
#     if: ${{ github.ref_name != 'master' }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push - AMD64 - UNSTABLE
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           file: infra/docker/Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:X64_${{ env.APP_DEV_VERSION }}
#           platforms: linux/amd64
      
#       - name: Build and push - ARM64 - UNSTABLE
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: infra/docker/ARM64.Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:ARM64_${{ env.APP_DEV_VERSION }}
#           platforms: linux/arm64

## Enable to deploy in master branch
#   production:
#     runs-on: ubuntu-latest
#     needs: test
#     if: ${{ github.ref_name == 'master' && github.event_name != 'pull_request' }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push - AMD64 - PROD
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           file: infra/docker/Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:X64_${{ env.APP_VERSION }}
#           platforms: linux/amd64

#       - name: Build and push - ARM64 - PROD
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: infra/docker/ARM64.Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:ARM64_${{ env.APP_VERSION }}
#           platforms: linux/arm64